# -*- mode: ruby -*-
# vi: set ft=ruby :

VM_NAME = "weblogic-centos6-12.1.3.0.0"
VM_BOX = "blinkesto/virtualbox-centos6"
PROJECT_ROOT="/Users/kdooley/IdeaProjects/rpm/weblogic_rpm"

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.require_version ">= 1.7.4"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.ssh.insert_key = false
    config.vm.box = VM_BOX

    # To enable dhcp go to Global Tools > vboxnet1 > DHCP Server > Enable
    config.vm.network 'private_network', ip: "192.168.56.4"
    config.vm.network "forwarded_port", guest: 7001, host: 7001
    config.vm.hostname = VM_NAME
    config.vm.synced_folder PROJECT_ROOT + "/files", "/mnt/files"
    config.vm.synced_folder PROJECT_ROOT + "/out", "/out"


    config.vm.provider :virtualbox do |vb|
        vb.name = VM_NAME

        vb.customize [ "modifyvm", :id, "--natdnshostresolver1", "on"]
            vb.customize [ "modifyvm", :id, "--natdnsproxy1", "on"]
            vb.customize [ "modifyvm", :id, "--nic2", "hostonly", "--hostonlyadapter2", "vboxnet1"]
            vb.customize [ "modifyvm", :id, "--memory", 1024]
            vb.customize [ "modifyvm", :id, "--cpus", 2]
            # vb.customize [ "modifyvm", :id, "--groups", "/weblogic_rpm"]
    end

    config.vm.provision "shell", path: "files/weblogic/install.sh"
end